branches:
  only: [development]
sudo: false

language: cpp
compiler: gcc
cache: ccache
dist: trusty

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-6
      - g++-6
      - libtbb-dev
      - libace-dev
      - cmake
      - make

before_script:
  - [ $TRAVIS_OS_NAME == 'linux' ] && export CC=/usr/lib/ccache/gcc-6; export CXX=/usr/lib/ccache/g++-6
  - $CC  --version
  - $CXX --version
  - export TBB_ROOT_DIR=/usr/lib/tbb
  - export ACE_ROOT=/usr/lib/ace

script: |-
  mkdir build
  cd build
  cmake -DDEBUG=0 ..
  make
