branches:
  only: [development]
sudo: false

language: cpp
compiler: gcc
cache: ccache
dist: trusty

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-6
      - g++-6
      - cmake
      - libtbb-dev
      - libace-dev
      - make

before_script:
  - if [ $TRAVIS_OS_NAME == 'linux' ]; then export CXX=/usr/bin/g++-6; export CC=/usr/bin/g++-6 fi
  - $CC  --version
  - $CXX --version
  - export TBB_ROOT_DIR=/usr/lib/tbb
  - export ACE_ROOT=/usr/lib/ace

script: |-
  mkdir build
  cd build
  cmake -DDEBUG=0 ..
  make
