branches:
  only: [development]
sudo: false

language: cpp
compiler: gcc
cache: ccache
dist: trusty

os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - gcc-6
      - g++-6
      - cmake
      - libtbb-dev
      - libace-dev
      - make

before_script:
  - if [ $TRAVIS_OS_NAME == 'inux' ]; then export CXX=/usr/bin/g++-6; export CC=/usr/bin/g++-6
  - $CC  --version
  - $CXX --version
  - export TBB_ROOT_DIR=/usr/lib/tbb
  - export ACE_ROOT=/usr/lib/ace

before_script:
  # g++6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: |-
  mkdir build
  cd build
  cmake -DDEBUG=0 ..
  make
